# Generated by Django 5.1.7 on 2025-10-04 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'default_permissions': (), 'ordering': ['-created_at'], 'permissions': [('User_view', 'می\u200cتواند کاربران را مشاهده کند'), ('User_add', 'می\u200cتواند کاربر جدید ایجاد کند'), ('User_change', 'می\u200cتواند کاربران را تغییر دهد'), ('User_delete', 'می\u200cتواند کاربران را حذف کند'), ('User_manage_permissions', 'می\u200cتواند مجوزهای کاربران را مدیریت کند'), ('User_reset_password', 'می\u200cتواند رمز عبور کاربران را ریست کند'), ('User_activate_deactivate', 'می\u200cتواند کاربران را فعال/غیرفعال کند')], 'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربران'},
        ),
    ]
