# Generated by Django 5.1.7 on 2025-10-04 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='نامک')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('color', models.CharField(default='#3b82f6', max_length=20, verbose_name='رنگ')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='آیکون')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی خبر',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای اخبار',
                'ordering': ['name'],
                'permissions': [('NewsCategory_view', 'می\u200cتواند دسته\u200cبندی اخبار را مشاهده کند'), ('NewsCategory_add', 'می\u200cتواند دسته\u200cبندی خبر جدید ایجاد کند'), ('NewsCategory_change', 'می\u200cتواند دسته\u200cبندی اخبار را تغییر دهد'), ('NewsCategory_delete', 'می\u200cتواند دسته\u200cبندی اخبار را حذف کند')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='NewsTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='نام')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='نامک')),
                ('color', models.CharField(default='#6b7280', max_length=20, verbose_name='رنگ')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'تگ خبر',
                'verbose_name_plural': 'تگ\u200cهای اخبار',
                'ordering': ['name'],
                'permissions': [('NewsTag_view', 'می\u200cتواند تگ\u200cهای اخبار را مشاهده کند'), ('NewsTag_add', 'می\u200cتواند تگ جدید ایجاد کند'), ('NewsTag_change', 'می\u200cتواند تگ\u200cها را تغییر دهد'), ('NewsTag_delete', 'می\u200cتواند تگ\u200cها را حذف کند')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='نامک')),
                ('summary', models.TextField(max_length=500, verbose_name='خلاصه')),
                ('content', models.TextField(verbose_name='محتوا')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='news/images/', verbose_name='تصویر شاخص')),
                ('gallery', models.JSONField(blank=True, default=list, verbose_name='گالری تصاویر')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='عنوان متا')),
                ('meta_description', models.TextField(blank=True, max_length=300, verbose_name='توضیحات متا')),
                ('meta_keywords', models.CharField(blank=True, max_length=500, verbose_name='کلمات کلیدی')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('published', 'منتشر شده'), ('archived', 'آرشیو شده')], default='draft', max_length=20, verbose_name='وضعیت')),
                ('priority', models.CharField(choices=[('low', 'پایین'), ('normal', 'عادی'), ('high', 'بالا'), ('urgent', 'فوری')], default='normal', max_length=20, verbose_name='اولویت')),
                ('is_featured', models.BooleanField(default=False, verbose_name='ویژه')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='سنجاق شده')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انتشار')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انقضا')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید')),
                ('like_count', models.PositiveIntegerField(default=0, verbose_name='تعداد لایک')),
                ('share_count', models.PositiveIntegerField(default=0, verbose_name='تعداد اشتراک')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.newscategory', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'خبر',
                'verbose_name_plural': 'اخبار',
                'ordering': ['-is_pinned', '-published_at', '-created_at'],
                'permissions': [('News_view', 'می\u200cتواند اخبار را مشاهده کند'), ('News_add', 'می\u200cتواند خبر جدید ایجاد کند'), ('News_change', 'می\u200cتواند اخبار را تغییر دهد'), ('News_delete', 'می\u200cتواند اخبار را حذف کند'), ('News_publish', 'می\u200cتواند اخبار را منتشر کند'), ('News_feature', 'می\u200cتواند اخبار را ویژه کند'), ('News_analytics', 'می\u200cتواند آمار اخبار را مشاهده کند')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='NewsComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='محتوا')),
                ('is_approved', models.BooleanField(default=True, verbose_name='تأیید شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='news.news', verbose_name='خبر')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newscomment', verbose_name='پاسخ به')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نظر خبر',
                'verbose_name_plural': 'نظرات اخبار',
                'ordering': ['-created_at'],
                'permissions': [('NewsComment_view', 'می\u200cتواند نظرات اخبار را مشاهده کند'), ('NewsComment_add', 'می\u200cتواند نظر جدید ایجاد کند'), ('NewsComment_change', 'می\u200cتواند نظرات را تغییر دهد'), ('NewsComment_delete', 'می\u200cتواند نظرات را حذف کند'), ('NewsComment_moderate', 'می\u200cتواند نظرات را مدیریت کند')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='NewsTagRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.news', verbose_name='خبر')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.newstag', verbose_name='تگ')),
            ],
            options={
                'verbose_name': 'رابطه خبر و تگ',
                'verbose_name_plural': 'رابطه\u200cهای خبر و تگ',
                'default_permissions': (),
                'unique_together': {('news', 'tag')},
            },
        ),
    ]
