# Generated by Django 5.1.7 on 2025-10-04 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'default_permissions': (), 'ordering': ['-is_featured', '-created_at'], 'permissions': [('Service_view', 'می\u200cتواند خدمات را مشاهده کند'), ('Service_add', 'می\u200cتواند خدمت جدید ایجاد کند'), ('Service_change', 'می\u200cتواند خدمات را تغییر دهد'), ('Service_delete', 'می\u200cتواند خدمات را حذف کند'), ('Service_feature', 'می\u200cتواند خدمات را ویژه کند'), ('Service_publish', 'می\u200cتواند خدمات را منتشر کند'), ('Service_analytics', 'می\u200cتواند آمار خدمات را مشاهده کند')]},
        ),
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'default_permissions': (), 'permissions': [('ServiceCategory_view', 'می\u200cتواند دسته\u200cبندی خدمات را مشاهده کند'), ('ServiceCategory_add', 'می\u200cتواند دسته\u200cبندی خدمت جدید ایجاد کند'), ('ServiceCategory_change', 'می\u200cتواند دسته\u200cبندی خدمات را تغییر دهد'), ('ServiceCategory_delete', 'می\u200cتواند دسته\u200cبندی خدمات را حذف کند')], 'verbose_name_plural': 'Service Categories'},
        ),
    ]
