# Generated by Django 5.1.7 on 2025-10-04 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_service_options_alter_servicecategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='تصویر بنر'),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.servicecategory', verbose_name='دسته\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='service',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='service',
            name='deliverables',
            field=models.JSONField(blank=True, default=list, verbose_name='تحویلی\u200cها'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='service',
            name='estimated_duration',
            field=models.CharField(blank=True, max_length=100, verbose_name='مدت زمان تخمینی'),
        ),
        migrations.AlterField(
            model_name='service',
            name='features',
            field=models.JSONField(blank=True, default=list, verbose_name='ویژگی\u200cها'),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(blank=True, max_length=50, verbose_name='آیکون'),
        ),
        migrations.AlterField(
            model_name='service',
            name='inquiry_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد درخواست\u200cها'),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='ویژه'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price_currency',
            field=models.CharField(default='IRR', max_length=3, verbose_name='واحد پول'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price_unit',
            field=models.CharField(default='پروژه', max_length=50, verbose_name='واحد قیمت'),
        ),
        migrations.AlterField(
            model_name='service',
            name='process_steps',
            field=models.JSONField(blank=True, default=list, verbose_name='مراحل فرآیند'),
        ),
        migrations.AlterField(
            model_name='service',
            name='short_description',
            field=models.CharField(blank=True, max_length=300, verbose_name='توضیحات کوتاه'),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='نامک'),
        ),
        migrations.AlterField(
            model_name='service',
            name='starting_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='قیمت شروع'),
        ),
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('active', 'فعال'), ('coming_soon', 'به\u200cزودی'), ('limited', 'محدود')], default='active', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='service',
            name='tagline',
            field=models.CharField(blank=True, max_length=200, verbose_name='شعار'),
        ),
        migrations.AlterField(
            model_name='service',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='color',
            field=models.CharField(default='blue', max_length=20, verbose_name='رنگ'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='icon',
            field=models.CharField(blank=True, max_length=50, verbose_name='آیکون'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='نامک'),
        ),
    ]
