# Generated by Django 5.1.7 on 2025-10-04 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_service_banner_image_alter_service_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceinquiry',
            options={'default_permissions': (), 'ordering': ['-created_at'], 'permissions': [('ServiceInquiry_view', 'می\u200cتواند درخواست\u200cهای خدمات را مشاهده کند'), ('ServiceInquiry_add', 'می\u200cتواند درخواست خدمت جدید ایجاد کند'), ('ServiceInquiry_change', 'می\u200cتواند درخواست\u200cهای خدمات را تغییر دهد'), ('ServiceInquiry_delete', 'می\u200cتواند درخواست\u200cهای خدمات را حذف کند'), ('ServiceInquiry_respond', 'می\u200cتواند به درخواست\u200cهای خدمات پاسخ دهد'), ('ServiceInquiry_assign', 'می\u200cتواند درخواست\u200cهای خدمات را واگذار کند'), ('ServiceInquiry_analytics', 'می\u200cتواند آمار درخواست\u200cهای خدمات را مشاهده کند')], 'verbose_name': 'درخواست خدمت', 'verbose_name_plural': 'درخواست\u200cهای خدمات'},
        ),
        migrations.AlterField(
            model_name='serviceinquiry',
            name='budget_range',
            field=models.CharField(blank=True, max_length=100, verbose_name='محدوده بودجه'),
        ),
        migrations.AlterField(
            model_name='serviceinquiry',
            name='company',
            field=models.CharField(blank=True, max_length=100, verbose_name='شرکت'),
        ),
        migrations.AlterField(
            model_name='serviceinquiry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='serviceinquiry',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='serviceinquiry',
            name='inquiry_type',
            field=models.CharField(choices=[('consultation', 'مشاوره'), ('quote', 'درخواست قیمت'), ('general', 'سوال عمومی')], default='general', max_length=20, verbose_name='نوع درخواست'),
        ),
        migrations.AlterField(
            model_name='serviceinquiry',
            name='message',
            field=models.TextField(verbose_name='پیام'),
        ),
        migrations.AlterField(
            model_name='serviceinquiry',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='serviceinquiry',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='تلفن'),
        ),
        migrations.AlterField(
            model_name='serviceinquiry',
            name='priority',
            field=models.PositiveIntegerField(default=3, verbose_name='اولویت'),
        ),
        migrations.AlterField(
            model_name='serviceinquiry',
            name='project_details',
            field=models.JSONField(blank=True, default=dict, verbose_name='جزئیات پروژه'),
        ),
        migrations.AlterField(
            model_name='serviceinquiry',
            name='response_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پاسخ'),
        ),
        migrations.AlterField(
            model_name='serviceinquiry',
            name='response_sent',
            field=models.BooleanField(default=False, verbose_name='پاسخ ارسال شده'),
        ),
        migrations.AlterField(
            model_name='serviceinquiry',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='services.service', verbose_name='خدمت'),
        ),
        migrations.AlterField(
            model_name='serviceinquiry',
            name='status',
            field=models.CharField(choices=[('new', 'جدید'), ('contacted', 'تماس گرفته شده'), ('in_progress', 'در حال بررسی'), ('completed', 'تکمیل شده'), ('cancelled', 'لغو شده')], default='new', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='serviceinquiry',
            name='subject',
            field=models.CharField(max_length=200, verbose_name='موضوع'),
        ),
        migrations.AlterField(
            model_name='serviceinquiry',
            name='timeline',
            field=models.CharField(blank=True, max_length=100, verbose_name='زمان\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='serviceinquiry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
    ]
