# Generated by Django 5.0.1 on 2025-10-04 07:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام شهر')),
                ('is_capital', models.BooleanField(default=False, verbose_name='مرکز استان است؟')),
            ],
            options={
                'verbose_name': 'شهر',
                'verbose_name_plural': 'شهرها',
                'ordering': ['name'],
                'permissions': [('view_city', 'می\u200cتواند شهر را مشاهده کند'), ('add_city', 'می\u200cتواند شهر جدید اضافه کند'), ('change_city', 'می\u200cتواند شهر را تغییر دهد'), ('delete_city', 'می\u200cتواند شهر را حذف کند')],
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='MyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='نام گروه')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
            ],
            options={
                'verbose_name': 'گروه',
                'verbose_name_plural': 'گروه\u200cها',
                'db_table': 'accounts_mygroups',
                'ordering': ['name'],
                'permissions': [('MyGroup_can_view_group', 'می\u200cتواند گروه\u200cها را مشاهده کند'), ('MyGroup_can_add_group', 'می\u200cتواند گروه جدید اضافه کند'), ('MyGroup_can_edit_group', 'می\u200cتواند گروه را ویرایش کند'), ('MyGroup_can_delete_group', 'می\u200cتواند گروه را حذف کند')],
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام استان')),
                ('code', models.CharField(help_text='کد دو رقمی استان', max_length=2, unique=True, verbose_name='کد استان')),
            ],
            options={
                'verbose_name': 'استان',
                'verbose_name_plural': 'استان\u200cها',
                'ordering': ['name'],
                'permissions': [('view_province', 'می\u200cتواند استان را مشاهده کند'), ('add_province', 'می\u200cتواند استان جدید اضافه کند'), ('change_province', 'می\u200cتواند استان را تغییر دهد'), ('delete_province', 'می\u200cتواند استان را حذف کند')],
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='TimeLockModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lock_key', models.TextField(verbose_name='کلید قفل (رمزنگاری\u200cشده)')),
                ('hash_value', models.CharField(max_length=64, unique=True, verbose_name='هش مقدار تنظیم\u200cشده')),
                ('salt', models.CharField(max_length=32, unique=True, verbose_name='مقدار تصادفی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت فعال')),
                ('organization_name', models.CharField(default='پیش\u200cفرض', max_length=255, verbose_name='نام مجموعه')),
            ],
            options={
                'verbose_name': 'قفل سیستم',
                'verbose_name_plural': 'قفل سیستم',
                'permissions': [('TimeLockModel_view', 'نمایش قفل سیستم'), ('TimeLockModel_add', 'افزودن قفل سیستم'), ('TimeLockModel_update', 'ویرایش قفل سیستم'), ('TimeLockModel_delete', 'حذف قفل سیستم')],
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='نام کاربری')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='ایمیل کاربر')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='نام کوچک')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='فامیلی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعالیت')),
                ('is_staff', models.BooleanField(default=False, verbose_name='کارمندی؟')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='مجوزهای خاص برای این کاربر.', related_name='accounts_user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'کاربر سفارشی',
                'verbose_name_plural': 'کاربران سفارشی',
                'permissions': [('users_view_customuser', 'می\u200cتواند کاربران سفارشی را مشاهده کند'), ('users_add_customuser', 'می\u200cتواند کاربر سفارشی جدید اضافه کند'), ('users_change_customuser', 'می\u200cتواند کاربر سفارشی را تغییر دهد'), ('users_delete_customuser', 'می\u200cتواند کاربر سفارشی را حذف کند')],
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'افزودن'), ('read', 'نمایش'), ('update', 'بروزرسانی'), ('delete', 'حــذف')], max_length=10, verbose_name='عملیات کاربری')),
                ('view_name', models.CharField(max_length=255, verbose_name='نام ویو')),
                ('path', models.CharField(max_length=255, verbose_name='مسیر درخواست')),
                ('method', models.CharField(max_length=10, verbose_name='متد HTTP')),
                ('model_name', models.CharField(max_length=255, verbose_name='نام مدل')),
                ('object_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ابجکت')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان رخداد')),
                ('details', models.TextField(blank=True, verbose_name='ریزمشخصات')),
                ('changes', models.JSONField(blank=True, null=True, verbose_name='تغییرات')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='آدرس IP')),
                ('browser', models.CharField(blank=True, max_length=255, verbose_name='بروزر')),
                ('status_code', models.IntegerField(blank=True, null=True, verbose_name='وضعیت کد')),
                ('related_object', models.CharField(blank=True, max_length=255, null=True, verbose_name='شیء مرتبط')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'لاگ گیری از سیستم',
                'verbose_name_plural': 'لاگ گیری از سیستم',
                'db_table': 'accounts_audit_log',
                'ordering': ['-timestamp'],
                'permissions': [('AuditLog_view', 'می\u200cتواند لاگ\u200cها را مشاهده کند'), ('AuditLog_add', 'می\u200cتواند لاگ\u200cها را اضافه کند'), ('AuditLog_update', 'می\u200cتواند لاگ\u200cها را بروزرسانی کند'), ('AuditLog_delete', 'می\u200cتواند لاگ\u200cها را حذف کند')],
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='CustomUserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('mygroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.mygroup')),
            ],
            options={
                'verbose_name': 'افزودن کاربری',
                'verbose_name_plural': 'افزودن کاربری',
                'db_table': 'accounts_customuser_groups',
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='accounts_groups_set', through='accounts.CustomUserGroup', to='accounts.mygroup', verbose_name='عضویت در گروه'),
        ),
        migrations.CreateModel(
            name='CustomProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='نام خانوادگی')),
                ('phone_number', models.CharField(blank=True, max_length=15, verbose_name='شماره تلفن')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('address', models.TextField(blank=True, verbose_name='آدرس')),
                ('location', models.TextField(blank=True, verbose_name='موقعیت')),
                ('bio', models.TextField(blank=True, verbose_name='بیوگرافی')),
                ('zip_code', models.CharField(blank=True, max_length=10, verbose_name='کد پستی')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('theme', models.CharField(choices=[], default='default', max_length=20)),
                ('custom_theme_data', models.JSONField(blank=True, null=True, verbose_name='داده\u200cهای تم سفارشی')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='accounts.city', verbose_name='شهر')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='accounts.province', verbose_name='استان')),
            ],
            options={
                'verbose_name': 'پروفایل سفارشی',
                'verbose_name_plural': 'پروفایل\u200cهای سفارشی',
                'permissions': [('users_view_userprofile', 'می\u200cتواند پروفایل کاربران را مشاهده کند'), ('users_add_userprofile', 'می\u200cتواند پروفایل کاربری اضافه کند'), ('users_update_userprofile', 'می\u200cتواند پروفایل کاربر را تغییر دهد'), ('users_delete_userprofile', 'می\u200cتواند پروفایل کاربر را غیرفعال کند'), ('users_search_userprofile', 'می\u200cتواند پروفایل کاربر را جستجو کند')],
                'default_permissions': [],
            },
        ),
        migrations.AddField(
            model_name='city',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='accounts.province', verbose_name='استان'),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='عنوان نقش')),
                ('description', models.TextField(blank=True, max_length=400, null=True, verbose_name='توضیحات نقش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='accounts.role', verbose_name='نقش والدین')),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles', to='auth.permission', verbose_name='مجوزها')),
            ],
            options={
                'verbose_name': 'نقش',
                'verbose_name_plural': 'نقش\u200cها',
                'ordering': ['name'],
                'permissions': [('Role_create', 'می\u200cتواند نقش جدید ایجاد کند'), ('Role_view', 'می\u200cتواند نقش\u200cها را مشاهده کند'), ('Role_modify', 'می\u200cتواند نقش را تغییر دهد'), ('Role_delete ', 'می\u200cتواند نقش را حذف کند')],
                'default_permissions': [],
            },
        ),
        migrations.AddField(
            model_name='mygroup',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='mygroups', to='accounts.role', verbose_name='تعریف نقش'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='custom_users', to='accounts.role', verbose_name='نقش\u200cها'),
        ),
        migrations.CreateModel(
            name='ActiveUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, help_text='شناسه یکتا برای سشن کاربر', max_length=40, verbose_name='کلید سشن')),
                ('login_time', models.DateTimeField(auto_now_add=True, db_index=True, help_text='زمان ورود کاربر به سیستم', verbose_name='زمان ورود')),
                ('hashed_count', models.CharField(blank=True, help_text='هش تعداد کاربران فعال برای امنیت بیشتر', max_length=64, null=True, verbose_name='هش تعداد کاربران')),
                ('last_activity', models.DateTimeField(auto_now=True, db_index=True, help_text='آخرین زمان فعالیت کاربر', verbose_name='آخرین فعالیت')),
                ('user_ip', models.GenericIPAddressField(blank=True, help_text='آدرس IP کاربر در زمان ورود', null=True, verbose_name='آی\u200cپی کاربر')),
                ('user_agent', models.TextField(blank=True, default='', help_text='اطلاعات مرورگر یا دستگاه کاربر', null=True, verbose_name='مرورگر/دستگاه کاربر')),
                ('is_active', models.BooleanField(default=True, help_text='آیا این سشن هنوز فعال است؟', verbose_name='فعال')),
                ('logout_time', models.DateTimeField(blank=True, help_text='زمان خروج کاربر از سیستم، در صورت ثبت', null=True, verbose_name='زمان خروج')),
                ('user', models.ForeignKey(help_text='کاربری که این سشن به او تعلق دارد', on_delete=django.db.models.deletion.CASCADE, related_name='active_sessions', related_query_name='active_session', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'کاربر فعال',
                'verbose_name_plural': 'کاربران فعال',
                'ordering': ['-last_activity', 'user'],
                'permissions': [('activeuser_view', 'نمایش تعداد کاربر دارای مجوز برای کار در سیستم'), ('activeuser_add', 'افزودن تعداد کاربر دارای مجوز برای کار در سیستم'), ('activeuser_update', 'آپدیت تعداد کاربر دارای مجوز برای کار در سیستم'), ('activeuser_delete', 'حذف تعداد کاربر دارای مجوز برای کار در سیستم')],
                'default_permissions': [],
                'indexes': [models.Index(fields=['user'], name='idx_user'), models.Index(fields=['last_activity'], name='idx_last_activity')],
            },
        ),
        migrations.AddConstraint(
            model_name='activeuser',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_user_session', violation_error_message='هر کاربر تنها می\u200cتواند یک سشن فعال داشته باشد.'),
        ),
        migrations.AddConstraint(
            model_name='activeuser',
            constraint=models.CheckConstraint(check=models.Q(('login_time__lte', models.F('last_activity'))), name='check_login_before_activity', violation_error_message='هر کاربر تنها می\u200cتواند یک سشن فعال داشته باشد.'),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('name', 'province')},
        ),
    ]
