# Generated by Django 5.1.7 on 2025-10-04 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'default_permissions': [], 'ordering': ['name'], 'permissions': [('Role_view', 'می\u200cتواند نقش\u200cها را مشاهده کند'), ('Role_add', 'می\u200cتواند نقش جدید ایجاد کند'), ('Role_change', 'می\u200cتواند نقش\u200cها را تغییر دهد'), ('Role_delete', 'می\u200cتواند نقش\u200cها را حذف کند'), ('Role_assign_permissions', 'می\u200cتواند مجوزها را به نقش\u200cها تخصیص دهد')], 'verbose_name': 'نقش', 'verbose_name_plural': 'نقش\u200cها'},
        ),
    ]
