# Generated by Django 5.1.7 on 2025-10-04 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computation_engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='computationsession',
            options={'default_permissions': (), 'ordering': ['-created_at'], 'permissions': [('', '')], 'verbose_name': 'Computation Session', 'verbose_name_plural': 'Computation Sessions'},
        ),
    ]
