# Generated by Django 5.1.7 on 2025-10-04 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computation_engine', '0002_alter_computationsession_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='computationmetrics',
            options={'default_permissions': (), 'ordering': ['-date'], 'permissions': [('ComputationMetrics_view', 'می\u200cتواند متریک\u200cهای محاسباتی را مشاهده کند'), ('ComputationMetrics_add', 'می\u200cتواند متریک محاسباتی جدید ایجاد کند'), ('ComputationMetrics_change', 'می\u200cتواند متریک\u200cهای محاسباتی را تغییر دهد'), ('ComputationMetrics_delete', 'می\u200cتواند متریک\u200cهای محاسباتی را حذف کند'), ('ComputationMetrics_analytics', 'می\u200cتواند گزارش\u200cهای تحلیلی را مشاهده کند')], 'verbose_name': 'Computation Metrics', 'verbose_name_plural': 'Computation Metrics'},
        ),
        migrations.AlterModelOptions(
            name='computationresult',
            options={'default_permissions': (), 'ordering': ['-created_at'], 'permissions': [('ComputationResult_view', 'می\u200cتواند نتایج محاسباتی را مشاهده کند'), ('ComputationResult_add', 'می\u200cتواند نتیجه محاسباتی جدید ایجاد کند'), ('ComputationResult_change', 'می\u200cتواند نتایج محاسباتی را تغییر دهد'), ('ComputationResult_delete', 'می\u200cتواند نتایج محاسباتی را حذف کند'), ('ComputationResult_cache', 'می\u200cتواند کش نتایج را مدیریت کند')], 'verbose_name': 'Computation Result', 'verbose_name_plural': 'Computation Results'},
        ),
        migrations.AlterModelOptions(
            name='computationsession',
            options={'default_permissions': (), 'ordering': ['-created_at'], 'permissions': [('ComputationSession_view', 'می\u200cتواند جلسات محاسباتی را مشاهده کند'), ('ComputationSession_add', 'می\u200cتواند جلسه محاسباتی جدید ایجاد کند'), ('ComputationSession_change', 'می\u200cتواند جلسات محاسباتی را تغییر دهد'), ('ComputationSession_delete', 'می\u200cتواند جلسات محاسباتی را حذف کند'), ('ComputationSession_execute', 'می\u200cتواند محاسبات را اجرا کند'), ('ComputationSession_view_results', 'می\u200cتواند نتایج محاسبات را مشاهده کند'), ('ComputationSession_manage_queue', 'می\u200cتواند صف محاسبات را مدیریت کند')], 'verbose_name': 'Computation Session', 'verbose_name_plural': 'Computation Sessions'},
        ),
        migrations.AlterModelOptions(
            name='computationtemplate',
            options={'default_permissions': (), 'ordering': ['name'], 'permissions': [('ComputationTemplate_view', 'می\u200cتواند قالب\u200cهای محاسباتی را مشاهده کند'), ('ComputationTemplate_add', 'می\u200cتواند قالب محاسباتی جدید ایجاد کند'), ('ComputationTemplate_change', 'می\u200cتواند قالب\u200cهای محاسباتی را تغییر دهد'), ('ComputationTemplate_delete', 'می\u200cتواند قالب\u200cهای محاسباتی را حذف کند'), ('ComputationTemplate_use', 'می\u200cتواند از قالب\u200cهای محاسباتی استفاده کند'), ('ComputationTemplate_manage', 'می\u200cتواند قالب\u200cهای محاسباتی را مدیریت کند')], 'verbose_name': 'Computation Template', 'verbose_name_plural': 'Computation Templates'},
        ),
    ]
