# Generated by Django 5.1.7 on 2025-10-04 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computation_engine', '0003_alter_computationmetrics_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='computationsession',
            options={'default_permissions': (), 'ordering': ['-created_at'], 'permissions': [('ComputationSession_view', 'می\u200cتواند جلسات محاسباتی را مشاهده کند'), ('ComputationSession_add', 'می\u200cتواند جلسه محاسباتی جدید ایجاد کند'), ('ComputationSession_change', 'می\u200cتواند جلسات محاسباتی را تغییر دهد'), ('ComputationSession_delete', 'می\u200cتواند جلسات محاسباتی را حذف کند'), ('ComputationSession_execute', 'می\u200cتواند محاسبات را اجرا کند'), ('ComputationSession_view_results', 'می\u200cتواند نتایج محاسبات را مشاهده کند'), ('ComputationSession_manage_queue', 'می\u200cتواند صف محاسبات را مدیریت کند')], 'verbose_name': 'جلسه محاسباتی', 'verbose_name_plural': 'جلسات محاسباتی'},
        ),
    ]
