# Generated by Django 5.1.7 on 2025-10-04 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computation_engine', '0004_alter_computationsession_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='computationmetrics',
            options={'default_permissions': (), 'ordering': ['-date'], 'permissions': [('ComputationMetrics_view', 'می\u200cتواند متریک\u200cهای محاسباتی را مشاهده کند'), ('ComputationMetrics_add', 'می\u200cتواند متریک محاسباتی جدید ایجاد کند'), ('ComputationMetrics_change', 'می\u200cتواند متریک\u200cهای محاسباتی را تغییر دهد'), ('ComputationMetrics_delete', 'می\u200cتواند متریک\u200cهای محاسباتی را حذف کند'), ('ComputationMetrics_analytics', 'می\u200cتواند گزارش\u200cهای تحلیلی را مشاهده کند')], 'verbose_name': 'متریک محاسباتی', 'verbose_name_plural': 'متریک\u200cهای محاسباتی'},
        ),
        migrations.AlterModelOptions(
            name='computationresult',
            options={'default_permissions': (), 'ordering': ['-created_at'], 'permissions': [('ComputationResult_view', 'می\u200cتواند نتایج محاسباتی را مشاهده کند'), ('ComputationResult_add', 'می\u200cتواند نتیجه محاسباتی جدید ایجاد کند'), ('ComputationResult_change', 'می\u200cتواند نتایج محاسباتی را تغییر دهد'), ('ComputationResult_delete', 'می\u200cتواند نتایج محاسباتی را حذف کند'), ('ComputationResult_cache', 'می\u200cتواند کش نتایج را مدیریت کند')], 'verbose_name': 'نتیجه محاسباتی', 'verbose_name_plural': 'نتایج محاسباتی'},
        ),
        migrations.AlterModelOptions(
            name='computationtemplate',
            options={'default_permissions': (), 'ordering': ['name'], 'permissions': [('ComputationTemplate_view', 'می\u200cتواند قالب\u200cهای محاسباتی را مشاهده کند'), ('ComputationTemplate_add', 'می\u200cتواند قالب محاسباتی جدید ایجاد کند'), ('ComputationTemplate_change', 'می\u200cتواند قالب\u200cهای محاسباتی را تغییر دهد'), ('ComputationTemplate_delete', 'می\u200cتواند قالب\u200cهای محاسباتی را حذف کند'), ('ComputationTemplate_use', 'می\u200cتواند از قالب\u200cهای محاسباتی استفاده کند'), ('ComputationTemplate_manage', 'می\u200cتواند قالب\u200cهای محاسباتی را مدیریت کند')], 'verbose_name': 'قالب محاسباتی', 'verbose_name_plural': 'قالب\u200cهای محاسباتی'},
        ),
    ]
