# Generated by Django 5.1.7 on 2025-10-04 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'default_permissions': (), 'ordering': ['-created_at'], 'permissions': [('Ticket_view', 'می\u200cتواند تیکت\u200cها را مشاهده کند'), ('Ticket_add', 'می\u200cتواند تیکت جدید ایجاد کند'), ('Ticket_change', 'می\u200cتواند تیکت\u200cها را تغییر دهد'), ('Ticket_delete', 'می\u200cتواند تیکت\u200cها را حذف کند'), ('Ticket_assign', 'می\u200cتواند تیکت\u200cها را تخصیص دهد'), ('Ticket_resolve', 'می\u200cتواند تیکت\u200cها را حل کند'), ('Ticket_close', 'می\u200cتواند تیکت\u200cها را ببندد'), ('Ticket_escalate', 'می\u200cتواند تیکت\u200cها را ارتقا دهد')], 'verbose_name': 'تیکت پشتیبانی', 'verbose_name_plural': 'تیکت\u200cهای پشتیبانی'},
        ),
        migrations.AlterModelOptions(
            name='ticketattachment',
            options={'default_permissions': (), 'ordering': ['-created_at'], 'permissions': [('TicketAttachment_view', 'می\u200cتواند فایل\u200cهای پیوست را مشاهده کند'), ('TicketAttachment_add', 'می\u200cتواند فایل پیوست جدید ایجاد کند'), ('TicketAttachment_change', 'می\u200cتواند فایل\u200cهای پیوست را تغییر دهد'), ('TicketAttachment_delete', 'می\u200cتواند فایل\u200cهای پیوست را حذف کند')], 'verbose_name': 'فایل پیوست', 'verbose_name_plural': 'فایل\u200cهای پیوست'},
        ),
        migrations.AlterModelOptions(
            name='ticketcategory',
            options={'default_permissions': (), 'ordering': ['name'], 'permissions': [('TicketCategory_view', 'می\u200cتواند دسته\u200cبندی تیکت\u200cها را مشاهده کند'), ('TicketCategory_add', 'می\u200cتواند دسته\u200cبندی تیکت جدید ایجاد کند'), ('TicketCategory_change', 'می\u200cتواند دسته\u200cبندی تیکت\u200cها را تغییر دهد'), ('TicketCategory_delete', 'می\u200cتواند دسته\u200cبندی تیکت\u200cها را حذف کند')], 'verbose_name': 'دسته\u200cبندی تیکت', 'verbose_name_plural': 'دسته\u200cبندی\u200cهای تیکت'},
        ),
        migrations.AlterModelOptions(
            name='ticketreply',
            options={'default_permissions': (), 'ordering': ['created_at'], 'permissions': [('TicketReply_view', 'می\u200cتواند پاسخ\u200cهای تیکت را مشاهده کند'), ('TicketReply_add', 'می\u200cتواند پاسخ تیکت جدید ایجاد کند'), ('TicketReply_change', 'می\u200cتواند پاسخ\u200cهای تیکت را تغییر دهد'), ('TicketReply_delete', 'می\u200cتواند پاسخ\u200cهای تیکت را حذف کند')], 'verbose_name': 'پاسخ تیکت', 'verbose_name_plural': 'پاسخ\u200cهای تیکت'},
        ),
    ]
