# Generated by Django 5.1.7 on 2025-10-04 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apiconfiguration',
            options={'default_permissions': (), 'permissions': [('APIConfiguration_view', 'می\u200cتواند تنظیمات API را مشاهده کند'), ('APIConfiguration_change', 'می\u200cتواند تنظیمات API را تغییر دهد'), ('APIConfiguration_manage', 'می\u200cتواند تنظیمات API را مدیریت کند')], 'verbose_name': 'API Configuration', 'verbose_name_plural': 'API Configurations'},
        ),
        migrations.AlterModelOptions(
            name='featureflag',
            options={'default_permissions': (), 'ordering': ['name'], 'permissions': [('FeatureFlag_view', 'می\u200cتواند پرچم\u200cهای ویژگی را مشاهده کند'), ('FeatureFlag_add', 'می\u200cتواند پرچم ویژگی جدید ایجاد کند'), ('FeatureFlag_change', 'می\u200cتواند پرچم\u200cهای ویژگی را تغییر دهد'), ('FeatureFlag_delete', 'می\u200cتواند پرچم\u200cهای ویژگی را حذف کند'), ('FeatureFlag_toggle', 'می\u200cتواند پرچم\u200cهای ویژگی را فعال/غیرفعال کند')], 'verbose_name': 'Feature Flag', 'verbose_name_plural': 'Feature Flags'},
        ),
        migrations.AlterModelOptions(
            name='fontsettings',
            options={'default_permissions': (), 'ordering': ['-is_default', '-is_active', 'name'], 'permissions': [('FontSettings_view', 'می\u200cتواند تنظیمات فونت\u200cها را مشاهده کند'), ('FontSettings_add', 'می\u200cتواند تنظیمات فونت جدید ایجاد کند'), ('FontSettings_change', 'می\u200cتواند تنظیمات فونت\u200cها را تغییر دهد'), ('FontSettings_delete', 'می\u200cتواند تنظیمات فونت\u200cها را حذف کند'), ('FontSettings_activate', 'می\u200cتواند تنظیمات فونت\u200cها را فعال کند')], 'verbose_name': 'تنظیمات فونت', 'verbose_name_plural': 'تنظیمات فونت\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'default_permissions': (), 'permissions': [('SiteSettings_view', 'می\u200cتواند تنظیمات سایت را مشاهده کند'), ('SiteSettings_change', 'می\u200cتواند تنظیمات سایت را تغییر دهد'), ('SiteSettings_manage', 'می\u200cتواند تنظیمات سایت را مدیریت کند')], 'verbose_name': 'Site Settings', 'verbose_name_plural': 'Site Settings'},
        ),
        migrations.AlterModelOptions(
            name='sitetemplate',
            options={'default_permissions': (), 'ordering': ['-is_default', 'template_type', 'name'], 'permissions': [('SiteTemplate_view', 'می\u200cتواند قالب\u200cهای سایت را مشاهده کند'), ('SiteTemplate_add', 'می\u200cتواند قالب سایت جدید ایجاد کند'), ('SiteTemplate_change', 'می\u200cتواند قالب\u200cهای سایت را تغییر دهد'), ('SiteTemplate_delete', 'می\u200cتواند قالب\u200cهای سایت را حذف کند'), ('SiteTemplate_activate', 'می\u200cتواند قالب\u200cهای سایت را فعال کند')], 'verbose_name': 'قالب سایت', 'verbose_name_plural': 'قالب\u200cهای سایت'},
        ),
    ]
