# Generated by Django 5.1.7 on 2025-10-04 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0002_alter_apiconfiguration_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apiconfiguration',
            options={'default_permissions': (), 'permissions': [('APIConfiguration_view', 'می\u200cتواند تنظیمات API را مشاهده کند'), ('APIConfiguration_change', 'می\u200cتواند تنظیمات API را تغییر دهد'), ('APIConfiguration_manage', 'می\u200cتواند تنظیمات API را مدیریت کند')], 'verbose_name': 'تنظیمات API', 'verbose_name_plural': 'تنظیمات\u200cهای API'},
        ),
        migrations.AlterModelOptions(
            name='featureflag',
            options={'default_permissions': (), 'ordering': ['name'], 'permissions': [('FeatureFlag_view', 'می\u200cتواند پرچم\u200cهای ویژگی را مشاهده کند'), ('FeatureFlag_add', 'می\u200cتواند پرچم ویژگی جدید ایجاد کند'), ('FeatureFlag_change', 'می\u200cتواند پرچم\u200cهای ویژگی را تغییر دهد'), ('FeatureFlag_delete', 'می\u200cتواند پرچم\u200cهای ویژگی را حذف کند'), ('FeatureFlag_toggle', 'می\u200cتواند پرچم\u200cهای ویژگی را فعال/غیرفعال کند')], 'verbose_name': 'پرچم ویژگی', 'verbose_name_plural': 'پرچم\u200cهای ویژگی'},
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'default_permissions': (), 'permissions': [('SiteSettings_view', 'می\u200cتواند تنظیمات سایت را مشاهده کند'), ('SiteSettings_change', 'می\u200cتواند تنظیمات سایت را تغییر دهد'), ('SiteSettings_manage', 'می\u200cتواند تنظیمات سایت را مدیریت کند')], 'verbose_name': 'تنظیمات سایت', 'verbose_name_plural': 'تنظیمات سایت'},
        ),
    ]
