# Generated by Django 5.0.1 on 2025-10-04 07:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('full_name', models.CharField(max_length=100, verbose_name='نام کامل')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='تلفن')),
                ('company', models.CharField(blank=True, max_length=100, verbose_name='شرکت')),
                ('job_title', models.CharField(blank=True, max_length=100, verbose_name='سمت')),
                ('preferred_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ترجیحی')),
                ('preferred_time', models.CharField(blank=True, max_length=50, verbose_name='زمان ترجیحی')),
                ('demo_type', models.CharField(default='online', max_length=50, verbose_name='نوع دمو')),
                ('special_requirements', models.TextField(blank=True, verbose_name='نیازهای خاص')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('scheduled', 'زمان\u200cبندی شده'), ('completed', 'تکمیل شده'), ('cancelled', 'لغو شده')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت\u200cها')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_demos', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'درخواست دمو',
                'verbose_name_plural': 'درخواست\u200cهای دمو',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PricingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('full_name', models.CharField(max_length=100, verbose_name='نام کامل')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='تلفن')),
                ('company', models.CharField(max_length=100, verbose_name='شرکت')),
                ('job_title', models.CharField(blank=True, max_length=100, verbose_name='سمت')),
                ('user_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد کاربر')),
                ('deployment_type', models.CharField(default='cloud', max_length=50, verbose_name='نوع استقرار')),
                ('custom_requirements', models.TextField(verbose_name='نیازهای سفارشی')),
                ('budget_range', models.CharField(blank=True, max_length=50, verbose_name='محدوده بودجه')),
                ('timeline', models.CharField(blank=True, max_length=100, verbose_name='زمان\u200cبندی')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('quoted', 'قیمت\u200cگذاری شده'), ('accepted', 'پذیرفته شده'), ('rejected', 'رد شده')], default='pending', max_length=20)),
                ('quoted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='IRR', max_length=3)),
                ('response_notes', models.TextField(blank=True, verbose_name='یادداشت\u200cهای پاسخ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_quotes', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'درخواست قیمت',
                'verbose_name_plural': 'درخواست\u200cهای قیمت',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.CharField(max_length=20, verbose_name='شماره نسخه')),
                ('version_type', models.CharField(choices=[('major', 'Major Release'), ('minor', 'Minor Update'), ('patch', 'Patch/Bug Fix'), ('beta', 'Beta Release'), ('alpha', 'Alpha Release')], default='minor', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('deprecated', 'Deprecated'), ('coming_soon', 'Coming Soon'), ('beta', 'Beta Testing')], default='active', max_length=20)),
                ('release_date', models.DateTimeField(verbose_name='تاریخ انتشار')),
                ('changelog', models.TextField(verbose_name='لیست تغییرات')),
                ('release_notes', models.TextField(blank=True, verbose_name='یادداشت\u200cهای انتشار')),
                ('system_requirements', models.JSONField(blank=True, default=dict)),
                ('file_size_mb', models.PositiveIntegerField(blank=True, null=True)),
                ('download_url', models.URLField(blank=True, verbose_name='لینک دانلود')),
                ('is_free', models.BooleanField(default=False, verbose_name='رایگان')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='IRR', max_length=3)),
                ('has_trial', models.BooleanField(default=False, verbose_name='نسخه آزمایشی')),
                ('trial_days', models.PositiveIntegerField(default=30, verbose_name='روزهای آزمایشی')),
                ('trial_download_url', models.URLField(blank=True, verbose_name='لینک دانلود آزمایشی')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='تعداد دانلود')),
                ('trial_count', models.PositiveIntegerField(default=0, verbose_name='تعداد آزمایش')),
                ('is_featured', models.BooleanField(default=False, verbose_name='ویژه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='products.product')),
            ],
            options={
                'verbose_name': 'نسخه محصول',
                'verbose_name_plural': 'نسخه\u200cهای محصول',
                'ordering': ['-release_date', '-version_number'],
                'unique_together': {('product', 'version_number')},
            },
        ),
        migrations.CreateModel(
            name='DownloadSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('download_type', models.CharField(choices=[('full', 'Full Download'), ('trial', 'Trial Download'), ('demo', 'Demo Download')], max_length=10)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('download_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('download_duration_seconds', models.FloatField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.productversion')),
            ],
            options={
                'verbose_name': 'جلسه دانلود',
                'verbose_name_plural': 'جلسات دانلود',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('source', models.CharField(choices=[('website', 'وب\u200cسایت'), ('demo_request', 'درخواست دمو'), ('pricing_request', 'درخواست قیمت'), ('trial_download', 'دانلود آزمایشی'), ('contact_form', 'فرم تماس'), ('referral', 'معرفی'), ('social_media', 'شبکه\u200cهای اجتماعی')], max_length=20)),
                ('status', models.CharField(choices=[('new', 'جدید'), ('contacted', 'تماس گرفته شده'), ('qualified', 'صلاحیت\u200cدار'), ('proposal', 'پیشنهاد'), ('negotiation', 'مذاکره'), ('closed_won', 'بسته شده - موفق'), ('closed_lost', 'بسته شده - ناموفق')], default='new', max_length=20)),
                ('full_name', models.CharField(max_length=100, verbose_name='نام کامل')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='تلفن')),
                ('company', models.CharField(blank=True, max_length=100, verbose_name='شرکت')),
                ('job_title', models.CharField(blank=True, max_length=100, verbose_name='سمت')),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='IRR', max_length=3)),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت\u200cها')),
                ('last_contact_date', models.DateTimeField(blank=True, null=True)),
                ('next_follow_up', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
                ('product_interest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
            ],
            options={
                'verbose_name': 'سرنخ فروش',
                'verbose_name_plural': 'سرنخ\u200cهای فروش',
                'ordering': ['-created_at'],
            },
        ),
    ]
