# Generated by Django 5.1.7 on 2025-10-04 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='demorequest',
            options={'default_permissions': (), 'ordering': ['-created_at'], 'permissions': [('DemoRequest_view', 'می\u200cتواند درخواست\u200cهای دمو را مشاهده کند'), ('DemoRequest_add', 'می\u200cتواند درخواست دمو جدید ایجاد کند'), ('DemoRequest_change', 'می\u200cتواند درخواست\u200cهای دمو را تغییر دهد'), ('DemoRequest_delete', 'می\u200cتواند درخواست\u200cهای دمو را حذف کند'), ('DemoRequest_schedule', 'می\u200cتواند درخواست\u200cهای دمو را زمان\u200cبندی کند'), ('DemoRequest_assign', 'می\u200cتواند درخواست\u200cهای دمو را تخصیص دهد')], 'verbose_name': 'درخواست دمو', 'verbose_name_plural': 'درخواست\u200cهای دمو'},
        ),
        migrations.AlterModelOptions(
            name='downloadsession',
            options={'default_permissions': (), 'ordering': ['-started_at'], 'permissions': [('DownloadSession_view', 'می\u200cتواند جلسات دانلود را مشاهده کند'), ('DownloadSession_add', 'می\u200cتواند جلسه دانلود جدید ایجاد کند'), ('DownloadSession_change', 'می\u200cتواند جلسات دانلود را تغییر دهد'), ('DownloadSession_delete', 'می\u200cتواند جلسات دانلود را حذف کند'), ('DownloadSession_analytics', 'می\u200cتواند آمار دانلودها را مشاهده کند')], 'verbose_name': 'جلسه دانلود', 'verbose_name_plural': 'جلسات دانلود'},
        ),
        migrations.AlterModelOptions(
            name='pricingrequest',
            options={'default_permissions': (), 'ordering': ['-created_at'], 'permissions': [('PricingRequest_view', 'می\u200cتواند درخواست\u200cهای قیمت را مشاهده کند'), ('PricingRequest_add', 'می\u200cتواند درخواست قیمت جدید ایجاد کند'), ('PricingRequest_change', 'می\u200cتواند درخواست\u200cهای قیمت را تغییر دهد'), ('PricingRequest_delete', 'می\u200cتواند درخواست\u200cهای قیمت را حذف کند'), ('PricingRequest_quote', 'می\u200cتواند درخواست\u200cهای قیمت را قیمت\u200cگذاری کند'), ('PricingRequest_assign', 'می\u200cتواند درخواست\u200cهای قیمت را تخصیص دهد')], 'verbose_name': 'درخواست قیمت', 'verbose_name_plural': 'درخواست\u200cهای قیمت'},
        ),
        migrations.AlterModelOptions(
            name='productversion',
            options={'default_permissions': (), 'ordering': ['-release_date', '-version_number'], 'permissions': [('ProductVersion_view', 'می\u200cتواند نسخه\u200cهای محصولات را مشاهده کند'), ('ProductVersion_add', 'می\u200cتواند نسخه محصول جدید ایجاد کند'), ('ProductVersion_change', 'می\u200cتواند نسخه\u200cهای محصولات را تغییر دهد'), ('ProductVersion_delete', 'می\u200cتواند نسخه\u200cهای محصولات را حذف کند'), ('ProductVersion_publish', 'می\u200cتواند نسخه\u200cهای محصولات را منتشر کند'), ('ProductVersion_analytics', 'می\u200cتواند آمار نسخه\u200cها را مشاهده کند')], 'verbose_name': 'نسخه محصول', 'verbose_name_plural': 'نسخه\u200cهای محصول'},
        ),
        migrations.AlterModelOptions(
            name='saleslead',
            options={'default_permissions': (), 'ordering': ['-created_at'], 'permissions': [('SalesLead_view', 'می\u200cتواند سرنخ\u200cهای فروش را مشاهده کند'), ('SalesLead_add', 'می\u200cتواند سرنخ فروش جدید ایجاد کند'), ('SalesLead_change', 'می\u200cتواند سرنخ\u200cهای فروش را تغییر دهد'), ('SalesLead_delete', 'می\u200cتواند سرنخ\u200cهای فروش را حذف کند'), ('SalesLead_qualify', 'می\u200cتواند سرنخ\u200cهای فروش را صلاحیت\u200cدار کند'), ('SalesLead_assign', 'می\u200cتواند سرنخ\u200cهای فروش را تخصیص دهد'), ('SalesLead_analytics', 'می\u200cتواند آمار سرنخ\u200cهای فروش را مشاهده کند')], 'verbose_name': 'سرنخ فروش', 'verbose_name_plural': 'سرنخ\u200cهای فروش'},
        ),
    ]
