# Generated by Django 5.1.7 on 2025-10-04 17:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productcategory_options'),
        ('sales', '0002_alter_demorequest_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleslead',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL, verbose_name='واگذار شده به'),
        ),
        migrations.AlterField(
            model_name='saleslead',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='saleslead',
            name='currency',
            field=models.CharField(default='IRR', max_length=3, verbose_name='واحد پول'),
        ),
        migrations.AlterField(
            model_name='saleslead',
            name='estimated_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='ارزش تخمینی'),
        ),
        migrations.AlterField(
            model_name='saleslead',
            name='last_contact_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخرین تماس'),
        ),
        migrations.AlterField(
            model_name='saleslead',
            name='lead_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='شناسه سرنخ'),
        ),
        migrations.AlterField(
            model_name='saleslead',
            name='next_follow_up',
            field=models.DateTimeField(blank=True, null=True, verbose_name='پیگیری بعدی'),
        ),
        migrations.AlterField(
            model_name='saleslead',
            name='product_interest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product', verbose_name='محصول مورد علاقه'),
        ),
        migrations.AlterField(
            model_name='saleslead',
            name='source',
            field=models.CharField(choices=[('website', 'وب\u200cسایت'), ('demo_request', 'درخواست دمو'), ('pricing_request', 'درخواست قیمت'), ('trial_download', 'دانلود آزمایشی'), ('contact_form', 'فرم تماس'), ('referral', 'معرفی'), ('social_media', 'شبکه\u200cهای اجتماعی')], max_length=20, verbose_name='منبع'),
        ),
        migrations.AlterField(
            model_name='saleslead',
            name='status',
            field=models.CharField(choices=[('new', 'جدید'), ('contacted', 'تماس گرفته شده'), ('qualified', 'صلاحیت\u200cدار'), ('proposal', 'پیشنهاد'), ('negotiation', 'مذاکره'), ('closed_won', 'بسته شده - موفق'), ('closed_lost', 'بسته شده - ناموفق')], default='new', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='saleslead',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
    ]
