# Generated by Django 5.0.1 on 2025-10-04 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='نام دسته\u200cبندی محصولات', max_length=100, verbose_name='نام دسته\u200cبندی')),
                ('slug', models.SlugField(blank=True, help_text='نامک برای استفاده در آدرس (خودکار تولید می\u200cشود)', unique=True, verbose_name='نامک URL')),
                ('description', models.TextField(blank=True, help_text='توضیحات کامل درباره دسته\u200cبندی', verbose_name='توضیحات')),
                ('icon', models.CharField(blank=True, help_text='نام آیکون FontAwesome (مثال: brain, shield)', max_length=50, verbose_name='آیکون')),
                ('color', models.CharField(default='blue', help_text='رنگ دسته\u200cبندی برای نمایش', max_length=20, verbose_name='رنگ')),
                ('is_active', models.BooleanField(default=True, help_text='آیا این دسته\u200cبندی فعال باشد؟', verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Product Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='نام محصول (مثال: BudgetPro، SecureAI)', max_length=100, verbose_name='نام محصول')),
                ('slug', models.SlugField(blank=True, help_text='نامک برای استفاده در آدرس (خودکار تولید می\u200cشود)', unique=True, verbose_name='نامک URL')),
                ('brand_prefix', models.CharField(default='TakoTech', help_text='پیشوند نام برند (مثال: TakoTech)', max_length=20, verbose_name='پیشوند برند')),
                ('tagline', models.CharField(blank=True, help_text='شعار کوتاه و جذاب برای محصول', max_length=200, verbose_name='شعار محصول')),
                ('description', models.TextField(help_text='توضیحات کامل و جامع محصول', verbose_name='توضیحات کامل')),
                ('short_description', models.CharField(blank=True, help_text='توضیحات کوتاه برای نمایش در فهرست\u200cها', max_length=300, verbose_name='توضیحات کوتاه')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('beta', 'بتا'), ('coming_soon', 'به\u200cزودی')], default='active', help_text='وضعیت فعلی محصول', max_length=20, verbose_name='وضعیت')),
                ('logo', models.ImageField(blank=True, help_text='تصویر لوگو محصول (PNG یا JPG)', null=True, upload_to='products/logos/', verbose_name='لوگو محصول')),
                ('banner_image', models.ImageField(blank=True, help_text='تصویر بنر اصلی محصول', null=True, upload_to='products/banners/', verbose_name='تصویر بنر')),
                ('features', models.JSONField(blank=True, default=list, help_text='لیست ویژگی\u200cهای محصول (JSON)', verbose_name='ویژگی\u200cها')),
                ('technical_specs', models.JSONField(blank=True, default=dict, help_text='مشخصات فنی محصول (JSON)', verbose_name='مشخصات فنی')),
                ('has_free_version', models.BooleanField(default=False, help_text='آیا این محصول نسخه رایگان دارد؟', verbose_name='نسخه رایگان')),
                ('has_trial', models.BooleanField(default=True, help_text='آیا این محصول نسخه آزمایشی دارد؟', verbose_name='نسخه آزمایشی')),
                ('trial_days', models.PositiveIntegerField(default=14, help_text='تعداد روزهای آزمایش رایگان', verbose_name='مدت آزمایشی (روز)')),
                ('view_count', models.PositiveIntegerField(default=0, help_text='تعداد بازدیدهای محصول', verbose_name='تعداد بازدید')),
                ('download_count', models.PositiveIntegerField(default=0, help_text='تعداد دانلودهای محصول', verbose_name='تعداد دانلود')),
                ('is_featured', models.BooleanField(default=False, help_text='آیا این محصول در بخش ویژه نمایش داده شود؟', verbose_name='محصول ویژه')),
                ('is_active', models.BooleanField(default=True, help_text='آیا این محصول فعال باشد؟', verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('category', models.ForeignKey(help_text='دسته\u200cبندی محصول', on_delete=django.db.models.deletion.CASCADE, to='products.productcategory', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
    ]
