# Generated by Django 5.1.7 on 2025-10-04 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'default_permissions': (), 'ordering': ['-is_featured', '-created_at'], 'permissions': [('Product_view', 'می\u200cتواند محصولات را مشاهده کند'), ('Product_add', 'می\u200cتواند محصول جدید ایجاد کند'), ('Product_change', 'می\u200cتواند محصولات را تغییر دهد'), ('Product_delete', 'می\u200cتواند محصولات را حذف کند'), ('Product_feature', 'می\u200cتواند محصولات را ویژه کند'), ('Product_publish', 'می\u200cتواند محصولات را منتشر کند'), ('Product_analytics', 'می\u200cتواند آمار محصولات را مشاهده کند')], 'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'default_permissions': (), 'permissions': [('ProductCategory_view', 'می\u200cتواند دسته\u200cبندی محصولات را مشاهده کند'), ('ProductCategory_add', 'می\u200cتواند دسته\u200cبندی محصول جدید ایجاد کند'), ('ProductCategory_change', 'می\u200cتواند دسته\u200cبندی محصولات را تغییر دهد'), ('ProductCategory_delete', 'می\u200cتواند دسته\u200cبندی محصولات را حذف کند')], 'verbose_name_plural': 'Product Categories'},
        ),
    ]
