# Generated by Django 5.1.7 on 2025-10-04 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_options_alter_productcategory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'default_permissions': (), 'permissions': [('ProductCategory_view', 'می\u200cتواند دسته\u200cبندی محصولات را مشاهده کند'), ('ProductCategory_add', 'می\u200cتواند دسته\u200cبندی محصول جدید ایجاد کند'), ('ProductCategory_change', 'می\u200cتواند دسته\u200cبندی محصولات را تغییر دهد'), ('ProductCategory_delete', 'می\u200cتواند دسته\u200cبندی محصولات را حذف کند')], 'verbose_name': 'دسته\u200cبندی محصول', 'verbose_name_plural': 'دسته\u200cبندی\u200cهای محصولات'},
        ),
    ]
